name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: npm
          cache-dependency-path: extension/package-lock.json

      - run: npm ci
        working-directory: extension
      - run: npm run package:${{matrix.target}}
        working-directory: extension

      - uses: actions/upload-artifact@v4
        with:
          path: extension/out/${{matrix.target}}/code-expert-master-${{github.ref_name}}-${{matrix.target}}.zip
          name: code-expert-master-${{github.ref_name}}-${{matrix.target}}.zip


  build-rust:
    runs-on: ${{matrix.target.os}}
    strategy:
      matrix:
        target:
          - os: windows-latest
            bin: cx-lsp-controller.exe
            name: cx-lsp-controller-${{github.ref.name}}-windows-x86_64.exe

          - os: ubuntu-latest
            bin: cx-controller
            name: cx-lsp-controller-${{github.ref.name}}-linux-x86_64

    steps:
      - uses: actions/checkout@v4

      - run: cargo build --verbose --release
        working-directory: native-host

      - uses: actions/upload-artifact@v4
        with:
          path: native-host/target/release/${{matrix.target.bin}}
          name: ${{matrix.target.name}}

  release:
    runs-on: ubuntu-latest
    needs: 
      - build-ts
      - build-rust
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*

