name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: npm
          cache-dependency-path: extension/package-lock.json

      - run: npm ci
        working-directory: extension
      - run: npm run package:${{matrix.target}}
        working-directory: extension

      - uses: actions/upload-artifact@v4
        with:
          path: extension/out/${{matrix.target}}/code-expert-master-${{github.ref_name}}-${{matrix.target}}.zip
          name: code-expert-master-${{github.ref_name}}-${{matrix.target}}.zip


  build-rust:
    runs-on: ${{matrix.target.os}}
    strategy:
      matrix:
        target:
          - os: windows-latest
            extension: .exe
            os_string: x86_64-pc-windows-msvc

          - os: ubuntu-latest
            extension: null
            os_string: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - run: cargo build --verbose --release --target ${{matrix.target.os_string}}
        working-directory: native-host
        env:
          CX_VERSION: ${{github.ref_name}}
          CX_OS_STRING: ${{matrix.target.name}}
          RUSTFLAGS: -C target-feature=+crt-static

      - run: cp cx-lsp-controller${{matrix.target.extension}} cx-lsp-controller-${{matrix.target.os_string}}${{matrix.target.extension}}
        working-directory: native-host/target/${{matrix.target.os_string}}/release

      - uses: actions/upload-artifact@v4
        with:
          path: native-host/target/release/cx-lsp-controller-${{matrix.target.os_string}}${{matrix.target.extension}}
          name: ${{matrix.target.name}}

  release:
    runs-on: ubuntu-latest
    needs: 
      - build-ts
      - build-rust
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: release
        merge-multiple: true
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*

