name: Create Release
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p release

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: npm
          cache-dependency-path: extension/package-lock.json

      - run: npm ci
        working-directory: extension
      - run: npm run package:${{matrix.target}}
        working-directory: extension
      - run: cp extension/out/chrome/code-expert-master-${{github.ref_name}}-${{matrix.target}}.zip release


  build-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p release
      - run: |
          cargo build --verbose --release --target=${{matrix.target}}
          cp target/${{matrix.target}}/release/cx-lsp-controller ../release/cx-lsp-controller-${{github.ref.name}}-${{matrix.target}}
        working-directory: native-host

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*

