# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - extension/**
      - .github/workflows/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: extension

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: npm
        cache-dependency-path: ${{env.working-directory}}/package-lock.json
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm run package:firefox
      working-directory: ${{env.working-directory}}
    - run: npm run package:chrome
      working-directory: ${{env.working-directory}}
