name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - native-host/**
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: native-host

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ${{env.working-directory}}
      run: cargo build --verbose
